#!/usr/bin/env python3
"""Rebuild `crawler/data/us_jurisdictions.tsv` from the Census gazetteer files.

Run by hand, roughly once a year when a new gazetteer vintage ships:

    cd crawler && python3 scripts/refresh_jurisdictions.py

    # offline / re-runnable against zips already on disk
    python3 scripts/refresh_jurisdictions.py --counties-zip 2024_Gaz_counties_national.zip \\
        --places-zip 2024_Gaz_place_national.zip

The direction of the dependency matters: this script imports `apsi_crawler.jurisdictions` so the
committed `name_key` column is produced by the very function that later reads it. Runtime code
must never import this script — it only reads the TSV.

Place filter (decided from the 2024 vintage, 32,333 rows): the place file's LSAD column carries
16 codes. Three of them are statistical geographies with no government — 57 CDP (12,528 rows),
55 comunidad (214, PR) and 62 zona urbana (78, PR) — and they are dropped. Everything else is an
incorporated/governmental place and is kept: 25 city, 43 town, 47 village, 21 borough, 53 city
and borough, 37 municipality, 35 metro township, 00 balance/consolidated government, and the
one-off UG/CG/UC/MG/CN codes (Lexington-Fayette urban county, Macon-Bibb County, Ranson
corporation, ...). The cut is confirmed by the FUNCSTAT column: those three LSAD codes hold
exactly the 12,820 rows marked `S` (statistical entity) and no others.

The county file has no LSAD column and lists only county-equivalents, so every row is kept
(including Alaska census areas and the independent cities, which portals do issue bids for).
"""

import argparse
import csv
import datetime
import io
import sys
import urllib.request
import zipfile
from pathlib import Path


CRAWLER_DIR = Path(__file__).resolve().parents[1]
if str(CRAWLER_DIR) not in sys.path:
    sys.path.insert(0, str(CRAWLER_DIR))

from apsi_crawler.jurisdictions import BUNDLED_TABLE_PATH, TABLE_COLUMNS, name_key  # noqa: E402


GAZETTEER_BASE = "https://www2.census.gov/geo/docs/maps-data/data/gazetteer/2024_Gazetteer/"
COUNTIES_URL = GAZETTEER_BASE + "2024_Gaz_counties_national.zip"
PLACES_URL = GAZETTEER_BASE + "2024_Gaz_place_national.zip"

# Statistical geographies, not governments. See the module docstring for how this was decided.
DROPPED_PLACE_LSAD = {
    "57": "CDP",
    "55": "comunidad",
    "62": "zona urbana",
}

USER_AGENT = "apsi-crawler-refresh-jurisdictions/1.0 (+https://www2.census.gov/geo/docs/)"


def download(url, timeout=120):
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=timeout) as response:
        return response.read()


def read_gazetteer(payload):
    """Rows of the single .txt inside a gazetteer zip, with the padded headers/values trimmed."""
    with zipfile.ZipFile(io.BytesIO(payload) if isinstance(payload, bytes) else payload) as archive:
        members = [name for name in archive.namelist() if name.lower().endswith(".txt")]
        if len(members) != 1:
            raise SystemExit("expected exactly one .txt inside the gazetteer zip, got {0}".format(members))
        text = archive.read(members[0]).decode("utf-8-sig", errors="replace")
    reader = csv.DictReader(text.splitlines(), delimiter="\t")
    return [
        dict((key.strip(), (value or "").strip()) for key, value in row.items() if key)
        for row in reader
    ]


def _entry(level, row):
    name = row.get("NAME", "")
    return {
        "level": level,
        "geoid": row.get("GEOID", ""),
        "state": row.get("USPS", "").upper(),
        "name": name,
        "name_key": name_key(name),
    }


def select_counties(rows):
    """Every county-equivalent; the county gazetteer carries nothing else."""
    return [_entry("county", row) for row in rows]


def select_places(rows):
    """Incorporated/governmental places only — see DROPPED_PLACE_LSAD."""
    return [_entry("place", row) for row in rows if row.get("LSAD", "") not in DROPPED_PLACE_LSAD]


def usable(entries):
    """Rows the loader can actually index, plus the ones it would silently skip."""
    keep, skipped = [], []
    for entry in entries:
        if entry["geoid"] and entry["state"] and entry["name_key"]:
            keep.append(entry)
        else:
            skipped.append(entry)
    keep.sort(key=lambda item: (item["level"], item["geoid"]))
    return keep, skipped


def render_table(entries, generated_on, counties, places):
    header = [
        "# US counties and incorporated places, keyed for apsi_crawler.jurisdictions.",
        "# Generated by crawler/scripts/refresh_jurisdictions.py - do not hand-edit rows.",
        "# generated: {0}".format(generated_on),
        "# source_counties: {0}".format(COUNTIES_URL),
        "# source_places: {0}".format(PLACES_URL),
        "# place_filter: dropped LSAD {0} (statistical, not governments); every other LSAD kept.".format(
            ", ".join("{0}={1}".format(code, label) for code, label in sorted(DROPPED_PLACE_LSAD.items()))
        ),
        "# rows: {0} counties + {1} places".format(counties, places),
    ]
    lines = header + ["\t".join(TABLE_COLUMNS)]
    lines.extend("\t".join(entry[column] for column in TABLE_COLUMNS) for entry in entries)
    return "\n".join(lines) + "\n"


def read_previous(path):
    try:
        text = Path(path).read_text(encoding="utf-8")
    except OSError:
        return None
    rows = [line for line in text.splitlines() if line.strip() and not line.startswith("#")]
    return dict(
        ((row.get("level", ""), row.get("geoid", "")), row.get("name", ""))
        for row in csv.DictReader(rows, delimiter="\t")
    )


def summarize_change(previous, entries):
    """`{"added": [...], "removed": [...], "renamed": [...]}` keyed by (level, geoid)."""
    current = dict(((entry["level"], entry["geoid"]), entry["name"]) for entry in entries)
    added = sorted(key for key in current if key not in previous)
    removed = sorted(key for key in previous if key not in current)
    renamed = sorted(
        (key, previous[key], current[key]) for key in current if key in previous and previous[key] != current[key]
    )
    return {"added": added, "removed": removed, "renamed": renamed}


def _report(label, items, render, limit=10):
    print("  {0}: {1}".format(label, len(items)))
    for item in items[:limit]:
        print("      {0}".format(render(item)))
    if len(items) > limit:
        print("      ... and {0} more".format(len(items) - limit))


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--output", default=str(BUNDLED_TABLE_PATH), help="TSV to write")
    parser.add_argument("--counties-zip", default=None, help="local counties zip instead of downloading")
    parser.add_argument("--places-zip", default=None, help="local places zip instead of downloading")
    parser.add_argument("--timeout", type=float, default=120.0, help="download timeout in seconds")
    parser.add_argument("--dry-run", action="store_true", help="report the diff without writing")
    args = parser.parse_args(argv)

    def payload(local, url):
        if local:
            print("reading {0}".format(local))
            return Path(local).read_bytes()
        print("downloading {0}".format(url))
        data = download(url, timeout=args.timeout)
        print("  {0} bytes".format(len(data)))
        return data

    county_rows = read_gazetteer(payload(args.counties_zip, COUNTIES_URL))
    place_rows = read_gazetteer(payload(args.places_zip, PLACES_URL))

    counties, skipped_counties = usable(select_counties(county_rows))
    places, skipped_places = usable(select_places(place_rows))
    entries = counties + places

    print("counties: {0} rows in, {1} kept".format(len(county_rows), len(counties)))
    print(
        "places:   {0} rows in, {1} kept ({2} dropped as {3})".format(
            len(place_rows),
            len(places),
            len(place_rows) - len(places) - len(skipped_places),
            "/".join(sorted(DROPPED_PLACE_LSAD.values())),
        )
    )
    for entry in skipped_counties + skipped_places:
        print("  skipped (no usable key): {0} {1} {2}".format(entry["state"], entry["name"], entry["geoid"]))

    output = Path(args.output)
    previous = read_previous(output)
    table = render_table(entries, datetime.date.today().isoformat(), len(counties), len(places))

    if previous is None:
        print("no previous table at {0} - writing {1} rows".format(output, len(entries)))
    else:
        change = summarize_change(previous, entries)
        print("changes against the committed table ({0} rows):".format(len(previous)))
        _report("added", change["added"], lambda key: "{0} {1}".format(*key))
        _report("removed", change["removed"], lambda key: "{0} {1}".format(*key))
        _report("renamed", change["renamed"], lambda item: "{0} {1}: {2} -> {3}".format(item[0][0], item[0][1], item[1], item[2]))

    if args.dry_run:
        print("--dry-run: {0} left unchanged".format(output))
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(table, encoding="utf-8")
    print("wrote {0} ({1} rows, {2} bytes)".format(output, len(entries), len(table.encode("utf-8"))))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
