import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

describe("settings page", () => {
  it("shows the current account tier and feature access states", () => {
    const page = readFileSync(new URL("page.tsx", import.meta.url), "utf8");

    expect(page).toContain("useAuth");
    expect(page).toContain("FEATURE_ACCESS_ITEMS");
    expect(page).toContain("canUseFeature");
    expect(page).toContain("lockedFeatureMessage");
    expect(page).toContain("settings.currentPlan");
    expect(page).toContain("settings.featureAccess");
    expect(page).toContain("updateAccountProfile");
    expect(page).toContain("changePassword");
    expect(page).toContain("exportAccountData");
    expect(page).toContain("deleteAccount");
    expect(page).toContain("fetchAccountSubscription");
    expect(page).toContain("fetchBillingInvoices");
    expect(page).toContain("createBillingPortalSession");
    expect(page).toContain("createCheckoutSession");
    expect(page).toContain("cancelAccountSubscription");
    expect(page).toContain("fetchAccountWorkspace");
    expect(page).toContain("updateAccountWorkspace");
    expect(page).toContain("inviteWorkspaceMember");
    expect(page).toContain("resendWorkspaceInvitation");
    expect(page).toContain("revokeWorkspaceInvitation");
    expect(page).toContain("updateWorkspaceMemberRole");
    expect(page).toContain("setWorkspaceMemberStatus");
    expect(page).toContain("transferWorkspaceOwnership");
    expect(page).toContain("removeWorkspaceMember");
    expect(page).toContain("user?.email");
    expect(page).toContain("workspaceData");
    expect(page).toContain("settings.team");
    expect(page).toContain("settings.inviteMember");
    expect(page).toContain("settings.inviteUrl");
    expect(page).toContain("settings.changeRole");
    expect(page).toContain("settings.removeMember");
    expect(page).toContain("settings.disableMember");
    expect(page).toContain("settings.restoreMember");
    expect(page).toContain("settings.resendInvite");
    expect(page).toContain("settings.revokeInvite");
    expect(page).toContain("settings.inviteResent");
    expect(page).toContain("settings.inviteRevoked");
    expect(page).toContain("settings.inviteUrl");
    expect(page).toContain("settings.memberUpdated");
    expect(page).toContain("settings.memberRemoved");
    expect(page).toContain("settings.transferOwnership");
    expect(page).toContain("settings.exportAccountData");
    expect(page).toContain("settings.deleteAccount");
    expect(page).toContain("settings.ownerTransferRequired");
    expect(page).toContain("displayName");
    expect(page).toContain("refreshSession");
    expect(page).toContain("settings.billing");
    expect(page).toContain("settings.availablePlans");
    expect(page).toContain("settings.startCheckout");
    expect(page).toContain("settings.checkoutStarted");
    expect(page).toContain("settings.cancelSubscription");
    expect(page).toContain("settings.invoiceHistory");
    expect(page).toContain("settings.noInvoices");
    expect(page).toContain("settings.viewInvoice");
    expect(page).toContain("settings.manageBilling");
    expect(page).toContain("settings.portalStarted");
  });
});
