import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

describe("admin page", () => {
  it("renders user access controls alongside crawler operations", () => {
    const page = readFileSync(new URL("page.tsx", import.meta.url), "utf8");

    expect(page).toContain("listAdminUsers");
    expect(page).toContain("createAdminUser");
    expect(page).toContain("listAdminUserAuditLogs");
    expect(page).toContain("listAdminUserFeatureOverrides");
    expect(page).toContain("listAdminNotifications");
    expect(page).toContain("listAdminBidQaItems");
    expect(page).toContain("deliverAdminNotifications");
    expect(page).toContain("reconcileAdminSubscriptions");
    expect(page).toContain("updateAdminUserAccess");
    expect(page).toContain("updateAdminUserFeatureOverride");
    expect(page).toContain("updateAdminBidQaReview");
    expect(page).toContain("useAuth");
    expect(page).toContain("isAdmin");
    expect(page).toContain("isOperator");
    expect(page).toContain("canAccessAdminConsole");
    expect(page).toContain("canRunOperations");
    expect(page).toContain('t("admin.authLoading")');
    expect(page).toContain('t("admin.loginRequiredTitle")');
    expect(page).toContain('t("admin.forbiddenTitle")');
    expect(page).toContain("if (!canAccessAdminConsole) return");
    expect(page).toContain('t("admin.users")');
    expect(page).toContain('t("admin.crawler")');
    expect(page).toContain('t("admin.bidQa")');
    expect(page).toContain('t("admin.qualityScore")');
    expect(page).toContain('t("admin.archiveIssues")');
    expect(page).toContain('t("admin.markReviewed")');
    expect(page).toContain('t("admin.displayStatus")');
    expect(page).toContain('t("admin.publishBid")');
    expect(page).toContain('t("admin.suppressBid")');
    expect(page).toContain('t("admin.saveCorrections")');
    expect(page).toContain("correctionDrafts");
    expect(page).toContain("displayStatus");
    expect(page).toContain("correctionCount");
    expect(page).toContain('t("admin.crawlerAdapter_dedicated")');
    expect(page).toContain('t("admin.crawlerMaturity_verified")');
    expect(page).toContain("source.crawlerCapabilities");
    expect(page).toContain("source.crawlerBaseUrl");
    expect(page).toContain('t("admin.inviteUser")');
    expect(page).toContain('t("admin.temporaryPassword")');
    expect(page).toContain("invitationDraft");
    expect(page).toContain("handleCreateAdminUser");
    expect(page).toContain('t("admin.userAuditLogs")');
    expect(page).toContain('t("admin.auditFilterTarget")');
    expect(page).toContain('t("admin.auditFilterFeature")');
    expect(page).toContain('t("admin.allAuditActors")');
    expect(page).toContain('t("admin.allAuditActions")');
    expect(page).toContain("userAuditFilters");
    expect(page).toContain('t("admin.featureOverrides")');
    expect(page).toContain('t("admin.overrideReason")');
    expect(page).toContain('t("admin.overrideExpiresAt")');
    expect(page).toContain('t("admin.overrideExpired")');
    expect(page).toContain("featureOverrideReason");
    expect(page).toContain("featureOverrideExpiresAt");
    expect(page).toContain("userFilters");
    expect(page).toContain("featureOverrideUser");
    expect(page).toContain("USER_ROLES");
    expect(page).toContain("ACCOUNT_TIERS");
    expect(page).toContain('t("admin.notificationDelivery")');
    expect(page).toContain('t("admin.deliverNotifications")');
    expect(page).toContain('t("admin.reconcileSubscriptions")');
  });
});
